name: Auto merge main branch to dev branch
on:
  push:
    branches:
      - "master"
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          label_name: "Auto-merge master back to dev"
          from_branch: master
          target_branch: dev
          github_token: ${{ secrets.TOKEN }}
