name: Auto merge main branch to dev branch
on:
  push:
    branches:
      - "master"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.TOKEN }}
          source_ref: "master"
          target_branch: "dev"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"
